### ISSUE TITLE
BaseMultiItemQuickAdapter的setVisible()方法的失效

### ISSUE THREAD

**Issue by hxkdidi** [CymChad/BaseRecyclerViewAdapterHelper#1576]
使用最新版本2.9.30,列表有多个demo_id,使用setVisible(R.id.demo_id，false)并没有隐藏掉，旧版2.9.14没有这个问题.

**Comment by hxkdidi** [comment]
2.9.30测试没有出现了

**Comment by CymChad** [comment]
2.9.28
@CymChad CymChad released this 29 days ago · 8 commits to master since this release

fixbug Click no response quickly

Change the method setVisible --> setGone
The new method setVisible

setVisible:Set a view visibility to VISIBLE (true) or INVISIBLE (false).
setGone: Set a view visibility to VISIBLE (true) or GONE (false).

**Comment by CymChad** [comment]
这是更新日志  https://github.com/CymChad/BaseRecyclerViewAdapterHelper/releases

**Comment by hxkdidi** [comment]
谢谢了，建议兼容一下旧方法

**Comment by CymChad** [comment]
恩，这个我以后会注意的。感谢你的建议。

**Comment by hxkdidi** [comment]
框架非常好用哦
