### ISSUE TITLE
无法理解

### ISSUE THREAD

**Issue by ruanbaojun1105** [CymChad/BaseRecyclerViewAdapterHelper#1579]
![qgw0 2svirrlasv1vv1b1v](https://user-images.githubusercontent.com/7459297/30737625-e53ba2f4-9fb9-11e7-9581-5cd2aa6fcf73.png)

这是2.9.15版本的效果

升级到最新版本
【查看简评】那个区域位置竟然还保留着 我已经隐藏了的  2.9.15版本是好的  换最新的就出现这问题

**Comment by CymChad** [comment]
2.9.28
@CymChad CymChad released this on 24 Aug · 8 commits to master since this release

fixbug Click no response quickly

Change the method setVisible --> setGone
The new method setVisible

setVisible:Set a view visibility to VISIBLE (true) or INVISIBLE (false).
setGone: Set a view visibility to VISIBLE (true) or GONE (false).

**Comment by CymChad** [comment]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/releases  更新列表

**Comment by ruanbaojun1105** [comment]
你说的这种东西我认为是比较特殊的情况才会需要用到，所以一般人谁会这么使用？？？建议用特殊的方法名标记出来，而不是和默认的混用方法！

**Comment by CymChad** [comment]
恩 好的，十分抱歉。下次我会注意的。
