### ISSUE TITLE
请教BaseNodeAdapter如何在Activity里面设置点击事件

### ISSUE THREAD

**Issue by Biswangluo** [CymChad/BaseRecyclerViewAdapterHelper#3202]
我是一个折叠的树形列表 在BaseNodeProvider重写了onClick方法，我想子item如何在activity 里面调用呢
如果设置setOnItemClickListener 那折叠就失效了 我这个列表另一个activity 也要用，所以我想在activity 里面处理，目前手动写了监听 在activity 调用
![企业微信截图_20200530102410](https://user-images.githubusercontent.com/2362450/83317511-da858e00-a25f-11ea-86a2-880b490318fd.png)

**Comment by xiangli19930605** [comment]
有解决吗，我也有这种需求

**Comment by newlai913** [comment]
这个问题可以用setOnItemChildClickListener替换吧，当成子控件去处理

**Comment by 1006245347** [comment]
你重写provider()，可以用接口回调啊，我是在provider()里写，子控件点击事件要addChildClickViewIds（viewID）

**Comment by liuzhenxin2156** [comment]
我在 provider() 写   addChildClickViewIds(R.id.card_view_all);无效啊

**Comment by freezingwhisper** [comment]
setOnItemChildClickListener之类的似乎不好使，至少我这里是不行的。我的解决方法是定义一个接口，在创建继承自BaseNodeAdapter的自定义adapter时作为参数传入。按照demo示例，在自定义adapter的构造方法中应该使用addNodeProvider来添加所有子集/子集的子集相关provider，在最内层的privider构造器中传入listener，之后在此provider中重写onClick，调用listener的相应方法即可。这样在activity中创建adapter时就可以通过listener自定义点击事件了。

**Comment by everyline** [comment]
> 
> 
> setOnItemChildClickListener之类的似乎不好使，至少我这里是不行的。我的解决方法是定义一个接口，在创建继承自BaseNodeAdapter的自定义adapter时作为参数传入。按照demo示例，在自定义adapter的构造方法中应该使用addNodeProvider来添加所有子集/子集的子集相关provider，在最内层的privider构造器中传入listener，之后在此provider中重写onClick，调用listener的相应方法即可。这样在activity中创建adapter时就可以通过listener自定义点击事件了。

我能看看你写的逻辑吗 我现在点击事件完全不管用

**Comment by freezingwhisper** [comment]
不好意思现在才看到邮件……
具体逻辑见附件。代码很简单，只构造了一个两层的折叠列表。外层对应的是ParentNode和ParentProvider，内层对应的是ChildNode和ChildProvider，外层+内层共同组成NodeAdapter，可用于普通recyclerView使用。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CymChad/BaseRecyclerViewAdapterHelper"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月6日(星期五) 上午9:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CymChad/BaseRecyclerViewAdapterHelper] 请教BaseNodeAdapter如何在Activity里面设置点击事件 (#3202)





  
setOnItemChildClickListener之类的似乎不好使，至少我这里是不行的。我的解决方法是定义一个接口，在创建继承自BaseNodeAdapter的自定义adapter时作为参数传入。按照demo示例，在自定义adapter的构造方法中应该使用addNodeProvider来添加所有子集/子集的子集相关provider，在最内层的privider构造器中传入listener，之后在此provider中重写onClick，调用listener的相应方法即可。这样在activity中创建adapter时就可以通过listener自定义点击事件了。
  
我能看看你写的逻辑吗 我现在点击事件完全不管用
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Hubertzzz** [comment]
> 不好意思现在才看到邮件…… 具体逻辑见附件。代码很简单，只构造了一个两层的折叠列表。外层对应的是ParentNode和ParentProvider，内层对应的是ChildNode和ChildProvider，外层+内层共同组成NodeAdapter，可用于普通recyclerView使用。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "CymChad/BaseRecyclerViewAdapterHelper" ***@***.***&gt;; 发送时间:&nbsp;2021年8月6日(星期五) 上午9:30 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [CymChad/BaseRecyclerViewAdapterHelper] 请教BaseNodeAdapter如何在Activity里面设置点击事件 (#3202) setOnItemChildClickListener之类的似乎不好使，至少我这里是不行的。我的解决方法是定义一个接口，在创建继承自BaseNodeAdapter的自定义adapter时作为参数传入。按照demo示例，在自定义adapter的构造方法中应该使用addNodeProvider来添加所有子集/子集的子集相关provider，在最内层的privider构造器中传入listener，之后在此provider中重写onClick，调用listener的相应方法即可。这样在activity中创建adapter时就可以通过listener自定义点击事件了。 我能看看你写的逻辑吗 我现在点击事件完全不管用 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

您好，能麻烦看看您这部分怎么写的吗，github上看不到您的附件，我也遇到了同样的问题，感谢。

**Comment by alphater** [comment]
我今天也遇到这个问题，最终发现是设置问题，具体原因没深究，因为着急上线，具体如下：
1，addChildClickViewIds的id不能是根目录的id，如果想要整个item可点那就包一层吧；
2，Provider里的onClick去掉（需要在activity里实现的，header里的不用去除，因为基本上都要实现展开收齐的expandOrCollapse）；
3，在activity或fragment中添加addChildClickViewIds和setOnItemChildClickListener就行了。

最重要的是第1点，我之前一直设置的根目录的id，就是不生效，后面设置子view就生效了。
